-- 0050 — Activities: departments' daily pictures (ADR-0039, Bajaur — phase C1, photos).
--
-- A separate module with its own tables. Nothing here touches the incident event log, the
-- `evidence` table, seats, or the removed department layer (ADR-0029/0030/0031). These are not
-- emergency records: deleting them is allowed, so unlike `incident_event` and `evidence` the
-- post and media rows here ARE deleted — and every delete leaves one line in `activity_log`.
--
-- As with evidence (0012), the bytes live on disk; these rows hold a reference and a hash.
--
-- ⚠️ No guard, no RAISE at boot: only new tables and one nullable column.

BEGIN;

--------------------------------------------------------------------------------
-- 1. The Department list — Activities only (ADR-0039 §2)
--------------------------------------------------------------------------------
--
-- Shown as "Department". Used to file and filter posts and for nothing else: NO authority
-- attaches to it, and no operational code reads it. Retired, never deleted, so an old post
-- still names the department it was filed under.

CREATE TABLE IF NOT EXISTS activity_unit (
    unit_id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    name               text        NOT NULL CHECK (btrim(name) <> '' AND length(name) <= 120),
    created_at         timestamptz NOT NULL DEFAULT now(),
    created_by_person_id uuid      REFERENCES person(person_id),
    retired_at         timestamptz
);

-- Two live departments may not share a name (case-insensitive); a retired one frees it.
CREATE UNIQUE INDEX IF NOT EXISTS activity_unit_live_name
    ON activity_unit (lower(btrim(name))) WHERE retired_at IS NULL;

-- Each account's default department (ADR-0039 §2). A post may choose another.
ALTER TABLE person
    ADD COLUMN IF NOT EXISTS activity_unit_id uuid REFERENCES activity_unit(unit_id);

--------------------------------------------------------------------------------
-- 2. Posts and their media
--------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS activity_post (
    post_id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    unit_id            uuid        NOT NULL REFERENCES activity_unit(unit_id),
    author_person_id   uuid        NOT NULL REFERENCES person(person_id),
    -- The day the activity happened, as a district date. Never in the future — checked by the
    -- API against the district clock, not here, so a test can run on any day.
    activity_date      date        NOT NULL,
    caption            text        NOT NULL CHECK (btrim(caption) <> '' AND length(caption) <= 2000),
    place              text        CHECK (place IS NULL OR length(place) <= 200),
    created_at         timestamptz NOT NULL DEFAULT now(),
    -- Soft delete by the DC / DNC: hidden, kept in the Recycle bin, restorable.
    hidden_at          timestamptz,
    hidden_by_person_id uuid       REFERENCES person(person_id)
);

CREATE INDEX IF NOT EXISTS activity_post_by_time   ON activity_post (created_at DESC, post_id);
CREATE INDEX IF NOT EXISTS activity_post_by_unit   ON activity_post (unit_id, created_at DESC);
CREATE INDEX IF NOT EXISTS activity_post_by_author ON activity_post (author_person_id, created_at DESC);
CREATE INDEX IF NOT EXISTS activity_post_by_date   ON activity_post (activity_date);

CREATE TABLE IF NOT EXISTS activity_media (
    media_id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    post_id            uuid        NOT NULL REFERENCES activity_post(post_id) ON DELETE CASCADE,
    kind               text        NOT NULL CHECK (kind IN ('photo')),
    content_type       text        NOT NULL,
    byte_size          bigint      NOT NULL CHECK (byte_size > 0),
    sha256             text        NOT NULL CHECK (length(sha256) = 64),
    -- Relative to the Activities root, generated by the server — never taken from the client.
    stored_path        text        NOT NULL UNIQUE,
    -- A small copy for the list, made on the phone with the photo. Null if none was sent.
    thumb_path         text        UNIQUE,
    created_at         timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS activity_media_by_post ON activity_media (post_id, created_at);

--------------------------------------------------------------------------------
-- 3. The log — append-only (INV-06)
--------------------------------------------------------------------------------
--
-- Who did what, when. No foreign key to the post: a hard-deleted post leaves its log line
-- behind, and that line is the only trace — who deleted which post, and when. Never the media.

CREATE TABLE IF NOT EXISTS activity_log (
    log_id             uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    seq                bigserial   NOT NULL UNIQUE,
    type               text        NOT NULL CHECK (type IN (
                           'posted',
                           'photo_added',
                           'hidden',          -- soft delete (Recycle bin)
                           'restored',
                           'deleted',         -- hard delete
                           'unit_created',
                           'unit_renamed',
                           'unit_retired',
                           'default_unit_set'
                       )),
    actor_person_id    uuid        REFERENCES person(person_id),
    post_id            uuid,
    unit_id            uuid,
    detail             jsonb,
    recorded_at        timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS activity_log_by_time ON activity_log (recorded_at DESC);

CREATE OR REPLACE FUNCTION activity_log_reject_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'activity_log is append-only; % is not permitted.', TG_OP
        USING ERRCODE = 'restrict_violation';
END;
$$;

DROP TRIGGER IF EXISTS activity_log_no_update ON activity_log;
CREATE TRIGGER activity_log_no_update
    BEFORE UPDATE OR DELETE ON activity_log
    FOR EACH ROW
    EXECUTE FUNCTION activity_log_reject_mutation();

DROP TRIGGER IF EXISTS activity_log_no_truncate ON activity_log;
CREATE TRIGGER activity_log_no_truncate
    BEFORE TRUNCATE ON activity_log
    FOR EACH STATEMENT
    EXECUTE FUNCTION activity_log_reject_mutation();

INSERT INTO schema_migration (version) VALUES ('0050_activities')
ON CONFLICT (version) DO NOTHING;

COMMIT;
