-- 0053 — WhatsApp → Activities (ADR-0040, Bajaur — phase D).
--
-- Officers send photos and videos to the district's WhatsApp number. Three places they can land:
--
--   1. Straight onto an Activities post — a known sender (the phone matches an account) with a
--      default department and no open emergency. `activity_post.source` says it came by WhatsApp,
--      and `activity_media.wa_message_id` is Meta's id for the message, so a retried webhook is
--      never a second photo.
--   2. `activity_inbound` in state `asking` — the sender has an open emergency, and was asked
--      with two buttons whether this is a report for it or a daily activity. Nothing is decided
--      until they tap; after an hour without a tap it moves to the Pending list.
--   3. `activity_inbound` in state `pending` — the DC's Pending list: an unknown number, an
--      account with no default department, or a question nobody answered. The DC approves
--      (choosing account and department) or rejects (hard delete).
--
-- An inbound row holds the media of one sender within five minutes (an album) and becomes one
-- post. The bytes are downloaded from Meta on arrival, because its links expire; they live under
-- the Activities root like every other Activities file, and the rows hold a reference and a hash.
--
-- Nothing here touches the incident event log or `evidence`: when the officer taps "Emergency
-- report", the media takes exactly today's evidence path and the inbound rows are removed.
--
-- ⚠️ No guard, no RAISE at boot: new columns with safe defaults, new tables, a widened CHECK.

BEGIN;

ALTER TABLE activity_post
    ADD COLUMN IF NOT EXISTS source text NOT NULL DEFAULT 'app';
ALTER TABLE activity_post DROP CONSTRAINT IF EXISTS activity_post_source_check;
ALTER TABLE activity_post ADD CONSTRAINT activity_post_source_check
    CHECK (source IN ('app', 'whatsapp'));

-- Meta's id for the inbound message. Unique, so a webhook Meta retries is never a second photo.
ALTER TABLE activity_media
    ADD COLUMN IF NOT EXISTS wa_message_id text UNIQUE;

CREATE TABLE IF NOT EXISTS activity_inbound (
    inbound_id         uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    -- The sender, as `toE164` writes it (digits only, 92…).
    from_phone         text        NOT NULL,
    --   asking   — the sender was asked "emergency report or daily activity?"
    --   choosing — their tap is being applied right now (a second tap finds nothing to do)
    --   pending  — on the DC's Pending list
    state              text        NOT NULL CHECK (state IN ('asking', 'choosing', 'pending')),
    reason             text        CHECK (reason IS NULL OR reason IN (
                           'unknown_sender',   -- no account has this number
                           'no_department',    -- an account, but no default department
                           'not_allowed',      -- an account that may not post (suspended, denied)
                           'no_answer'         -- asked, and no tap within the hour
                       )),
    -- The account the number matched, when it matched one.
    person_id          uuid        REFERENCES person(person_id),
    -- The open emergency the sender was asked about, and our message the match came from.
    incident_id        uuid,
    matched_message_id text,
    asked_at           timestamptz,
    -- When `state` last changed: the hour without an answer, and a stuck `choosing`, run from here.
    state_at           timestamptz NOT NULL DEFAULT now(),
    created_at         timestamptz NOT NULL DEFAULT now(),
    -- When the latest media joined it: the five-minute album window runs from here.
    last_media_at      timestamptz NOT NULL DEFAULT now(),
    CHECK (state <> 'pending' OR reason IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS activity_inbound_by_sender
    ON activity_inbound (from_phone, state, last_media_at DESC);
CREATE INDEX IF NOT EXISTS activity_inbound_by_time
    ON activity_inbound (state, state_at);

CREATE TABLE IF NOT EXISTS activity_inbound_media (
    media_id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    inbound_id         uuid        NOT NULL REFERENCES activity_inbound(inbound_id) ON DELETE CASCADE,
    wa_message_id      text        UNIQUE,
    kind               text        NOT NULL CHECK (kind IN ('photo', 'video')),
    content_type       text        NOT NULL,
    byte_size          bigint      NOT NULL CHECK (byte_size > 0),
    sha256             text        NOT NULL CHECK (length(sha256) = 64),
    -- Relative to the Activities root, generated by the server.
    stored_path        text        NOT NULL UNIQUE,
    -- The words sent with it, if any — the post's caption, or the reply's words on an emergency.
    caption            text,
    -- The message of ours the officer used WhatsApp's reply control on, if they did.
    reply_context_id   text,
    received_at        timestamptz NOT NULL,
    created_at         timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS activity_inbound_media_by_inbound
    ON activity_inbound_media (inbound_id, received_at);

ALTER TABLE activity_log DROP CONSTRAINT IF EXISTS activity_log_type_check;
ALTER TABLE activity_log ADD CONSTRAINT activity_log_type_check CHECK (type IN (
    'posted',
    'photo_added',
    'video_added',
    'video_failed',
    'hidden',
    'restored',
    'deleted',
    'expired',
    'zip_downloaded',
    'unit_created',
    'unit_renamed',
    'unit_retired',
    'default_unit_set',
    'date_changed',       -- a post's activity date was changed
    'pending_approved',   -- the DC approved WhatsApp media from the Pending list
    'pending_rejected',   -- the DC rejected it (hard delete)
    'pending_expired'     -- it sat on the Pending list past the 30-day rule
));

INSERT INTO schema_migration (version) VALUES ('0053_whatsapp_activities')
ON CONFLICT (version) DO NOTHING;

COMMIT;
